# Generated by Django 3.2.3 on 2021-12-20 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candyuser',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('email_verified', 'Email Verified'), ('documents_uploaded', 'Documents Uploaded'), ('id_verified', 'ID Verified'), ('id_not_verified', 'ID Not Verified'), ('agreement_signed', 'Agreement Signed'), ('active', 'Active'), ('inactive', 'Inactive'), ('on_hold', 'On Hold')], default=('new', 'new'), max_length=20),
        ),
        migrations.CreateModel(
            name='UserEmailVeirfyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('verified', 'Verified')], max_length=20)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
