# Generated by Django 3.2.8 on 2021-12-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211220_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='candyuserprofile',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='candyuserprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
