# Generated by Django 3.2.9 on 2021-12-30 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_id', models.CharField(max_length=50)),
                ('isin', models.CharField(max_length=50, unique=True)),
                ('currency', models.CharField(blank=True, choices=[('usd', '$USD'), ('cad', '$CAD')], max_length=20, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('amount_for_sale', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('balance_on_deposit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bank_issue', models.CharField(blank=True, max_length=10, null=True)),
                ('interest_coupon', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('pending_desk_approval', 'Pending Desk Approval'), ('approved_for_sale', 'Approved For Sale'), ('sold', 'Sold'), ('on_hold', 'On Hold'), ('active', 'Active')], max_length=32, null=True)),
                ('bond_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_approve_for_sale', 'Can approve for sale'), ('can_change_status', 'Can change status')],
            },
        ),
    ]
